Repository HackHeaders/FrontEnd, pull requests merged in 2024-12, with the labels that each got.

#82 Responsiveness test
  src/components/RegisterClient/FormFirstStep.vue
  src/components/RegisterClient/FormSecondStep.vue
  src/components/RegisterClient/RegisterComp.vue
  src/components/admin/Dashboard/SectionCards.vue
  src/components/admin/Dashboard/graphs/FirstGraphsComp.vue
  src/components/admin/ManageAll/ManageAllComp.vue
  src/components/admin/ManageAll/ManagePeoples.vue
  src/components/admin/ManageAll/ManageVehicles.vue
  src/components/admin/RegisterDriver/FormFirstStep.vue
  src/components/admin/RegisterDriver/FormSecondStep.vue
  src/components/admin/RegisterDriver/FormThirdStep.vue
  src/components/admin/RegisterDriver/RegisterDriverComp.vue
  src/components/admin/RegisterEmployee/FormFirstStep.vue
  src/components/admin/RegisterEmployee/FormSecondStep.vue
  src/components/admin/RegisterEmployee/RegisterComp.vue
  src/components/client/ProfileClient/DoneOrders.vue
  src/components/client/ProfileClient/FinishedOrders.vue
  src/components/client/ProfileClient/PendingOrders.vue
  src/components/client/ProfileClient/ProfileComp.vue
  src/components/client/ProfileClient/RightProfileInputs.vue
  src/components/client/ProfileClient/TypeOrderComp.vue
  src/components/driver/DoneOrders.vue
  src/components/driver/FinishedOrders.vue
  src/components/driver/LeftProfileInputs.vue
  src/components/driver/PendingOrders.vue
  src/components/driver/ProfileComp.vue
  src/components/driver/RightProfileInputs.vue
  src/components/driver/TypeOrderComp.vue
  src/components/footer/AddressFooterComp.vue
  src/components/footer/ContactFooterComp.vue
  src/components/footer/FooterComp.vue
  src/components/footer/NavFooterComp.vue
  src/components/footer/SocialFooterComp.vue
  src/components/homeview/LastSection.vue
  src/components/login/LoginComp.vue
  src/components/login/LoginForm.vue
  src/plugins/index.js
  src/views/order/OrderStatusView.vue
  src/views/order/OrderView.vue
  src/views/order/index.js
Labels: Chore

#89 Dev
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-54d0af47.js
  generate-sitemap.mjs
  index.html
  package-lock.json
  package.json
  public/apple-touch-icon.png
  public/logo.png
  public/pwa-192x192.png
  public/pwa-512x512.png
  src/components/MakeOrder/FirstOrder.vue
  src/components/MakeOrder/FortOrder.vue
  src/components/MakeOrder/SecondOrder.vue
  src/components/MakeOrder/ThirdOrder.vue
  src/components/orderstatus/OrderModalComp.vue
  src/plugins/index.js
  src/router/index.js
  src/services/order/order.js
  src/stores/auth/auth.js
  src/stores/order/order.js
  vite.config.js
Labels: Feat, Version

#93 Feat 92
  dev-dist/sw.js
  dev-dist/workbox-7e873c62.js
  index.html
  src/components/MakeOrder/FirstOrder.vue
  src/components/MyDriverOrder/CurrentOrder.vue
  src/components/client/ProfileClient/TypeOrderComp.vue
  src/components/homeview/FirstSection.vue
  src/components/orderstatus/OrderStatusInformations.vue
  src/router/index.js
  src/services/order/order.js
  src/views/driver/MyDriverOrder.vue
  src/views/tests/Location.vue
Labels: Fix, Feat

#94 Dev
  dev-dist/sw.js
  dev-dist/workbox-7e873c62.js
  dev-dist/workbox-e7681877.js
  index.html
  package-lock.json
  public/robots.txt
  src/components/MakeOrder/FirstOrder.vue
  src/components/MakeOrder/FortOrder.vue
  src/components/MakeOrder/SecondOrder.vue
  src/components/MakeOrder/ThirdOrder.vue
  src/components/MyDriverOrder/CurrentOrder.vue
  src/components/VehiclesComponents/FirstSection.vue
  src/components/about/FourthSection.vue
  src/components/about/SecondSection.vue
  src/components/client/ProfileClient/TypeOrderComp.vue
  src/components/header/HeaderComp.vue
  src/components/homeview/FirstSection.vue
  src/components/orderstatus/OrderStatusInformations.vue
  src/router/index.js
  src/services/order/order.js
  src/stores/order/order.js
  src/views/driver/MyDriverOrder.vue
  src/views/tests/Location.vue
  vite.config.js
Labels: Fix, Feat, Chore
